### PR TITLE
Added PHPStorm .idea folder to .gitignore

### PR DESCRIPTION
**Pull request by micheleangioni**
Added PHPStorm .idea folder into .gitignore

### CODE REVIEW

**Comment by sergeyklay** [comment]
Please do not use this ignore file to define platform specific files.

For these purposes create a global .gitignore file, which is a list of rules for ignoring files in every Git repository on your computer.

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Review by sergeyklay — CHANGES_REQUESTED** [review]
-1 for .idea

**Comment by micheleangioni** [comment]
I agree that creating a global .gitignore file is a best practice and should be preferred! Nevertheless not everybody does it and we should aim to easy development to people who want to contribute. Imho this is especially true for a platform like Phalcon that really needs to find new contributors to its ecosystem :)

**Comment by zachleigh** [comment]
Please follow the advice of @sergeyklay. If we start adding platform/developer specific entries into .gitignore, it will soon start to get out of control.

**Comment by micheleangioni** [comment]
Ok :)

**Pull request closed without merging**
